### ISSUE TITLE
RunWavelengths() got an unexpected keyword argument 'tau'

### ISSUE THREAD

**Issue by QiaoFeng0419** [fnemina/pyOSOAA#25]
When i run `rho_toa, tau = RunWavelengths(s, wl/1e3, angle=view, tau=True)`, 
i get a exception `TypeError: RunWavelengths() got an unexpected keyword argument 'tau'`.
I find function `RunWavelengths` in your source code, but not see `tau` parameters.
If you update your local code, but not update to github?

**Comment by fnemina** [comment]
I just uploaded the code to github. Check it again.

**Comment by fnemina** [comment]
Solved.
