### ISSUE TITLE
I use the method you mentioned to compare NASA Seawifs Rayleigh lookup table with OSOAA Rayleigh scattering.

### ISSUE THREAD

**Issue by fnemina** [fnemina/pyOSOAA#26]
I use the method you mentioned to compare NASA Seawifs Rayleigh lookup table with OSOAA Rayleigh scattering.
But there are some differences between my results and yours.
My results:
![fig_Relative error](https://user-images.githubusercontent.com/15885479/61340370-9ae6cb00-a874-11e9-9c93-bfc53d5f87c9.png)
Relative error is as high as 10%.
My code is [here](https://github.com/QiaoFeng0419/Atmospheric-correction-for-GOCI/blob/master/Rayleigh/CompareRayleighBetweenOSOAAandSeaDAS.py)
So, i have some question:

1. The `tau` which in NASA Seawifs Rayleigh lookup table cannot be used to calculate transmittance because OSOAA has its own Tau.

2. What is the step size of the parameters in the Rayleigh scattering lookup table you generated? Can you share your code?

_Originally posted by @QiaoFeng0419 in https://github.com/fnemina/AtmosphericCorrection/issues/1#issuecomment-512065537_

**Comment by fnemina** [comment]
I moved your issue here because it will be more related to code here.

1. I've added here 2fa8a889d470292fdddd16b3f05b42e45040e39b the option for the RunWavelengths helper to use a custom Rayleigh optical thickness given by the user.  If you want to so it by hand the OSOAA method ap.setMot(taur) let's you input your own Rayleigh optical thickness.

Just change this line

```python
rho_t, tau = RunWavelengths(s, wl/1000, view, taur=True)/np.cos(np.pi*view/180.0)
```
to
```python
taur = ray.getTaur()
rho_t, tau = RunWavelengths(s, wl/1000, view, taur=taur)/np.cos(np.pi*view/180.0)
```
and it should work.
![Figure_1](https://user-images.githubusercontent.com/2727433/61412725-fc805700-a8bf-11e9-8107-434c6162a901.png)

Also, the getRadiance for Rayleigh that I coded doesn't returns normalized radiances. So you should normalize it too, by dividing by `np.cos(np.pi*view/180.0)`, or you should not normalize the radiances calculated by the OSOAA. Both options are fine but you should be consistent. Here are some plots for comparison.

![Figure_2](https://user-images.githubusercontent.com/2727433/61412735-03a76500-a8c0-11e9-9e44-f0f34676dc88.png)
_No normalization applied to OSOAA results_
![Figure_3](https://user-images.githubusercontent.com/2727433/61412743-0b670980-a8c0-11e9-8fdd-8e6a3986b9bf.png)
_Normalization only applied to OSOAA results_

[Here](https://github.com/fnemina/pyOSOAA/files/3403881/CompareRayleighBetweenOSOAAandSeaDAS.zip) is the code I used modifying yours.

2. As for the LUTs I generated, they are for a single wavelength yet, but I will implement the calculation for a band in the near future. Also, the number of data points used to compute the Fourier transform in phi was 11. Let me ask my boss about sharing this code and I'll write back to you.

Best regards
Fran

**Comment by QiaoFeng0419** [comment]
I think the biggest problem with the errors is that the results of getRadiance are not normalized.

The normalized results are much better.

Thank you.

**Comment by QiaoFeng0419** [comment]
Can your boss let you share the code that generates the lookup table?

**Comment by fnemina** [comment]
Hello Qiao Feng,
As long as both radiances are normalized or not normalized it's ok. I didn't normalize the getRadiance function because I am following the implementation of the seadas-L2Gen code and was going to do it at the end.

About the other code. We are evaluating it. The code is not yet in a stage to make it public. But I'll write back to you as soon as we can share it.
