### ISSUE TITLE
SED class has no default value

### ISSUE THREAD

**Issue by QiaoFeng0419** [fnemina/pyOSOAA#28]
When i set sediment concentration `s.sed.csed = 0.2`.
Error:
```
OSOAA_MAIN : ERROR_2640 on parameters
   -->  Junge model for Mineral-Like Particles
        is required (-Keyword Value)  : 
           -SED.JD.slope (Float): Slope.
           -SED.JD.MRwa (Float): 
                real part of refractive index.
           -SED.JD.MIwa (Float): 
                imaginary part of refractive index.
           -SED.JD.rate (Float): Ratio of this mode
                for Mineral-Like Particles.
```
There is no default value for this value in your source code, can you add it?

**Comment by fnemina** [comment]
A value was added for the Junge model 046f80bc59ec3de7dc306cfefdcd3d53b7af532e. 

Please run to configure it
```python
s.sed.csed = 0.2
s.sed.SetPrimaryMode()
s.run()
```

You can check  
[this paper](https://github.com/fnemina/pyOSOAA/files/3442416/42fbacd305a1ee630432c1d43494ec0248fa.pdf) for more valued for the refractive index.

**Comment by QiaoFeng0419** [comment]
Thank you. It's really good.
